name: Run Python Script

on:
  workflow_dispatch:  # Allows manual triggering via API or GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # You can change this

      - name: Install Dependencies (if any)
        run: |
          pip install -r requirements.txt || echo "No requirements.txt file found"

      - name: Run Python Script
        run: python script.py  # This runs the Python script
